# -*- coding: utf-8 -*-
"""Visualisasi Skripsi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oNZ6SwDb8MfLjY3Q-Nx6i-Ja6knfJ48_
"""

from google.colab import drive
drive.mount('/content/drive')

import os
import glob
import numpy as np
import rasterio
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap, BoundaryNorm

from rasterio.plot import show

plt.rcParams["figure.figsize"] = (8,6)

base_path = "/content/drive/MyDrive/Landsat"

experiments = {
    "2005": {"sensor": "L7", "folder": "2005"},
    "2010": {"sensor": "L7", "folder": "2010"},
    "2015": {"sensor": "L8", "folder": "2015"},
    "2025": {"sensor": "L8", "folder": "2025"},
    "Control 2005": {"sensor": "L7", "folder": "Control 2005"},
    "Control 2010": {"sensor": "L7", "folder": "Control 2010"},
    "Control 2015": {"sensor": "L8", "folder": "Control 2015"},
    "Control 2025": {"sensor": "L8", "folder": "Control 2025"}
}

import os
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap, BoundaryNorm

# ============================================================
# KONFIGURASI VISUALISASI
# ============================================================
bounds = [-1, 0, 0.2, 0.4, 0.6, 1]
colors = ['#2c7bb6', '#ffff66', '#66bd63', '#238b45', '#00441b']
labels = ['<0 (Air)', '0–0.2', '0.2–0.4', '0.4–0.6', '>0.6']
cmap = ListedColormap(colors)
cmap.set_bad(color='white')
norm = BoundaryNorm(bounds, cmap.N)

def print_area_stats(data, mask, title_prefix):
    """Menghitung dan mencetak statistik luasan area"""
    spatial_data = np.where(mask, data, np.nan)
    pixel_area = (30 * 30) / 1e6 # 30m resolution to km2

    print(f"\nStatistik Luasan - {title_prefix}:")

    # Hitung per kategori
    stats = {
        "Badan Air (<0)": np.nansum(spatial_data < 0),
        "Non-Vegetasi (0-0.2)": np.nansum((spatial_data >= 0) & (spatial_data < 0.2)),
        "Vegetasi Rendah (0.2-0.4)": np.nansum((spatial_data >= 0.2) & (spatial_data < 0.4)),
        "Vegetasi Sedang (0.4-0.6)": np.nansum((spatial_data >= 0.4) & (spatial_data < 0.6)),
        "Vegetasi Tinggi (>0.6)": np.nansum(spatial_data >= 0.6)
    }

    for cat, pixels in stats.items():
        km2 = pixels * pixel_area
        print(f"  - {cat}: {km2:.2f} km²")

def plot_ndvi_refined(data, mask, title):
    """Fungsi untuk plotting dengan masking dan cropping otomatis"""
    spatial_data = np.where(mask, data, np.nan)

    rows = np.any(~np.isnan(spatial_data), axis=1)
    cols = np.any(~np.isnan(spatial_data), axis=0)
    if not np.any(rows): return

    rmin, rmax = np.where(rows)[0][[0, -1]]
    cmin, cmax = np.where(cols)[0][[0, -1]]

    pad = 20
    rmin, rmax = max(0, rmin-pad), min(spatial_data.shape[0], rmax+pad)
    cmin, cmax = max(0, cmin-pad), min(spatial_data.shape[1], cmax+pad)

    cropped = spatial_data[rmin:rmax, cmin:cmax]

    fig, ax = plt.subplots(figsize=(10, 7))
    im = ax.imshow(cropped, cmap=cmap, norm=norm)

    cbar = plt.colorbar(im, ax=ax, orientation='horizontal', pad=0.1, fraction=0.04)
    tick_locs = [(bounds[i] + bounds[i+1])/2 for i in range(len(bounds)-1)]
    cbar.set_ticks(tick_locs)
    cbar.set_ticklabels(labels)
    cbar.set_label('Klasifikasi NDVI')

    ax.set_title(title, fontsize=14)
    ax.axis('off')
    plt.tight_layout()
    plt.show()

# ============================================================
# GENERASI 12 PETA & STATISTIK AREA
# ============================================================
target_years = ["2005", "2010", "2015", "2025"]

for year in target_years:
    print(f"\n{'='*40} ANALISIS TAHUN {year} {'='*40}")

    # Data & Mask
    ndvi_sid = results_ndvi[year]['ndvi']
    mask_sid = results_ndvi[year]['mask']

    ndvi_ctrl = results_ndvi[f'Control {year}']['ndvi']
    mask_ctrl = results_ndvi[f'Control {year}']['mask']

    mask_imp = mask_sid & (~mask_ctrl)

    # 1. Sidoarjo
    print_area_stats(ndvi_sid, mask_sid, f"Sidoarjo {year}")
    plot_ndvi_refined(ndvi_sid, mask_sid, f'Peta NDVI Kabupaten Sidoarjo Tahun {year}')

    # 2. Control
    print_area_stats(ndvi_ctrl, mask_ctrl, f"Control {year}")
    plot_ndvi_refined(ndvi_ctrl, mask_ctrl, f'Peta NDVI Wilayah Control Tahun {year}')

    # 3. Impact
    print_area_stats(ndvi_sid, mask_imp, f"Impact {year}")
    plot_ndvi_refined(ndvi_sid, mask_imp, f'Peta NDVI Zona Impact Sidoarjo Tahun {year}')

import pandas as pd

def get_stats_dict(data, mask):
    """Helper untuk mengambil statistik luasan sebagai dictionary"""
    spatial_data = np.where(mask, data, np.nan)
    pixel_area = (30 * 30) / 1e6

    return {
        "Badan Air": np.nansum(spatial_data < 0) * pixel_area,
        "Non-Vegetasi": np.nansum((spatial_data >= 0) & (spatial_data < 0.2)) * pixel_area,
        "Vegetasi Rendah": np.nansum((spatial_data >= 0.2) & (spatial_data < 0.4)) * pixel_area,
        "Vegetasi Sedang": np.nansum((spatial_data >= 0.4) & (spatial_data < 0.6)) * pixel_area,
        "Vegetasi Tinggi": np.nansum(spatial_data >= 0.6) * pixel_area
    }

# List untuk menampung data tabel
table_data = []

for year in target_years:
    # Ambil data dasar
    ndvi_sid = results_ndvi[year]['ndvi']
    mask_sid = results_ndvi[year]['mask']
    ndvi_ctrl = results_ndvi[f'Control {year}']['ndvi']
    mask_ctrl = results_ndvi[f'Control {year}']['mask']
    mask_imp = mask_sid & (~mask_ctrl)

    # Hitung stats untuk 3 kategori utama
    regions = {
        "Sidoarjo": (ndvi_sid, mask_sid),
        "Control": (ndvi_ctrl, mask_ctrl),
        "Impact": (ndvi_sid, mask_imp)
    }

    for region_name, (data, mask) in regions.items():
        stats = get_stats_dict(data, mask)
        row = {"Tahun": year, "Wilayah": region_name}
        row.update(stats)
        table_data.append(row)

# Membuat DataFrame
df_stats = pd.DataFrame(table_data)

# Menampilkan tabel yang difilter per Wilayah untuk kemudahan analisis
for region in ["Sidoarjo", "Control", "Impact"]:
    print(f"\n--- Ringkasan Luasan NDVI: {region} (km²) ---")
    display(df_stats[df_stats['Wilayah'] == region].drop(columns=['Wilayah']))

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap, BoundaryNorm
import rasterio
import glob
import os

# ============================================================
# 0. LOAD DATA BANDS (NIR & SWIR) - MAPPING DARI FILE TERPISAH
# ============================================================
results_bands = {}

for name, cfg in experiments.items():
    folder_path = os.path.join(base_path, cfg['folder'])

    # Mencari file spesifik berdasarkan nama band dalam folder
    nir_files = glob.glob(os.path.join(folder_path, "*NIR*.tif"))
    swir_files = glob.glob(os.path.join(folder_path, "*SWIR*.tif"))

    if not nir_files or not swir_files:
        print(f"Warning: NIR or SWIR file not found in {folder_path}")
        continue

    with rasterio.open(nir_files[0]) as src_nir:
        nir = src_nir.read(1).astype(float)

    with rasterio.open(swir_files[0]) as src_swir:
        swir = src_swir.read(1).astype(float)

    # Gunakan mask dari results_ndvi yang sudah dihitung sebelumnya
    mask = results_ndvi[name]['mask'] if name in results_ndvi else np.ones(nir.shape, dtype=bool)

    results_bands[name] = {
        'nir': nir,
        'swir': swir,
        'sidoarjo_mask': mask
    }

# ============================================================
# 1. KONFIGURASI VISUALISASI NDBI
# ============================================================
bounds_ndbi = [-1, 0, 0.1, 0.2, 0.3, 1]
colors_ndbi = ['#1a9641', '#a6d96a', '#ffffbf', '#fdae61', '#d7191c']
cmap_ndbi = ListedColormap(colors_ndbi)
cmap_ndbi.set_bad(color='white')
norm_ndbi = BoundaryNorm(bounds_ndbi, cmap_ndbi.N)

def plot_ndbi_refined(data, mask, title):
    spatial_data = np.where(mask, data, np.nan)
    rows = np.any(~np.isnan(spatial_data), axis=1)
    cols = np.any(~np.isnan(spatial_data), axis=0)
    if not np.any(rows): return
    rmin, rmax = np.where(rows)[0][[0, -1]]
    cmin, cmax = np.where(cols)[0][[0, -1]]
    pad = 20
    rmin, rmax = max(0, rmin-pad), min(spatial_data.shape[0], rmax+pad)
    cmin, cmax = max(0, cmin-pad), min(spatial_data.shape[1], cmax+pad)
    cropped = spatial_data[rmin:rmax, cmin:cmax]

    fig, ax = plt.subplots(figsize=(10, 7))
    im = ax.imshow(cropped, cmap=cmap_ndbi, norm=norm_ndbi)
    cbar = plt.colorbar(im, ax=ax, orientation='horizontal', pad=0.1, fraction=0.04)
    cbar.set_label('Klasifikasi NDBI')
    ax.set_title(title, fontsize=14)
    ax.axis('off')
    plt.show()

# ============================================================
# 2. PROSES KALKULASI & VISUALISASI
# ============================================================
table_data_ndbi = []
pixel_area = (30 * 30) / 1e6

for year in ["2005", "2010", "2015", "2025"]:
    if year not in results_bands or f'Control {year}' not in results_bands: continue

    data_sid = results_bands[year]
    data_ctrl = results_bands[f'Control {year}']

    def calc_ndbi(d):
        num = (d['swir'] - d['nir'])
        den = (d['swir'] + d['nir'])
        return np.divide(num, den, out=np.full_like(num, np.nan), where=den!=0)

    ndbi_sid = calc_ndbi(data_sid)
    ndbi_ctrl = calc_ndbi(data_ctrl)
    mask_sid = data_sid['sidoarjo_mask']
    mask_ctrl = data_ctrl['sidoarjo_mask']
    mask_imp = mask_sid & (~mask_ctrl)

    regions = {"Sidoarjo": (ndbi_sid, mask_sid), "Control": (ndbi_ctrl, mask_ctrl), "Impact": (ndbi_sid, mask_imp)}

    for name, (data, mask) in regions.items():
        spatial = np.where(mask, data, np.nan)
        table_data_ndbi.append({
            "Tahun": year, "Wilayah": name,
            "Water/Veg (<0)": np.nansum(spatial < 0) * pixel_area,
            "Non-Built (0-0.1)": np.nansum((spatial >= 0) & (spatial < 0.1)) * pixel_area,
            "Low Built (0.1-0.2)": np.nansum((spatial >= 0.1) & (spatial < 0.2)) * pixel_area,
            "Med Built (0.2-0.3)": np.nansum((spatial >= 0.2) & (spatial < 0.3)) * pixel_area,
            "High Built (>0.3)": np.nansum(spatial >= 0.3) * pixel_area
        })
        plot_ndbi_refined(data, mask, f'Peta NDBI {name} Tahun {year}')

# ============================================================
# 3. RINGKASAN TABEL NDBI
# ============================================================
df_ndbi = pd.DataFrame(table_data_ndbi)
for region in ["Sidoarjo", "Control", "Impact"]:
    print(f"\n--- Ringkasan Luasan NDBI: {region} (km²) ---")
    display(df_ndbi[df_ndbi['Wilayah'] == region].drop(columns=['Wilayah']))

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import rasterio
import glob
import os

# ============================================================
# 0. UPDATE DATA BANDS (Memastikan Red & Thermal tersedia)
# ============================================================
for name, cfg in experiments.items():
    folder_path = os.path.join(base_path, cfg['folder'])
    red_f = glob.glob(os.path.join(folder_path, "*Red*.tif"))
    thermal_f = glob.glob(os.path.join(folder_path, "*Thermal*.tif"))

    if red_f and thermal_f:
        if name not in results_bands: results_bands[name] = {}
        with rasterio.open(red_f[0]) as src:
            results_bands[name]['red'] = src.read(1).astype(float)
        with rasterio.open(thermal_f[0]) as src:
            results_bands[name]['thermal'] = src.read(1).astype(float)

# ============================================================
# 1. FUNGSI ANALISIS & PLOTTING LST
# ============================================================
def get_lst_results(data, mask):
    nir, red, thermal = data['nir'], data['red'], data['thermal']
    ndvi = (nir - red) / (nir + red + 1e-10)
    pv = np.clip(((ndvi - 0.2) / (0.5 - 0.2))**2, 0, 1)
    lse = np.where(ndvi < 0, 0.985, np.where(ndvi <= 0.2, 0.97, np.where(ndvi <= 0.5, 0.986 + 0.004 * pv, 0.99)))
    t_nan = np.where(thermal <= 0, np.nan, thermal)
    bt = t_nan * 0.00341802 + 149.0
    l_val, rho = 10.895e-6, 1.438e-2
    lst_k = bt / (1 + (l_val * bt / rho) * np.log(np.clip(lse, 0.001, 1)))
    lst_c = lst_k - 273.15
    return np.where(mask, lst_c, np.nan), np.where(mask, pv, np.nan), np.where(mask, lse, np.nan)

def plot_lst_refined(lst_data, title):
    """Plotting LST dengan auto-cropping untuk konsistensi ukuran"""
    rows = np.any(~np.isnan(lst_data), axis=1)
    cols = np.any(~np.isnan(lst_data), axis=0)
    if not np.any(rows): return
    rmin, rmax = np.where(rows)[0][[0, -1]]
    cmin, cmax = np.where(cols)[0][[0, -1]]
    pad = 20
    rmin, rmax = max(0, rmin-pad), min(lst_data.shape[0], rmax+pad)
    cmin, cmax = max(0, cmin-pad), min(lst_data.shape[1], cmax+pad)
    cropped = lst_data[rmin:rmax, cmin:cmax]

    fig, ax = plt.subplots(figsize=(10, 7))
    im = ax.imshow(cropped, cmap='hot_r', vmin=20, vmax=50)
    cbar = plt.colorbar(im, ax=ax, label='LST (°C)', orientation='horizontal', pad=0.1, fraction=0.04)
    ax.set_title(title, fontsize=12)
    ax.axis('off')
    plt.tight_layout()
    plt.show()

# ============================================================
# 2. PROSES 12 PETA & PENYUSUNAN TABEL
# ============================================================
table_data_lst = []

for year in ["2005", "2010", "2015", "2025"]:
    if year not in results_bands: continue
    d_sid, d_ctrl = results_bands[year], results_bands[f'Control {year}']
    m_sid, m_ctrl = d_sid['sidoarjo_mask'], d_ctrl['sidoarjo_mask']
    m_imp = m_sid & (~m_ctrl)

    reg_map = {"Sidoarjo": (d_sid, m_sid), "Control": (d_ctrl, m_ctrl), "Impact": (d_sid, m_imp)}

    for name, (d_obj, m_obj) in reg_map.items():
        lst, pv, lse = get_lst_results(d_obj, m_obj)
        table_data_lst.append({
            "Tahun": year, "Wilayah": name,
            "PV Min": np.nanmin(pv), "PV Max": np.nanmax(pv),
            "LSE Min": np.nanmin(lse), "LSE Max": np.nanmax(lse),
            "LST Min": np.nanmin(lst), "LST Max": np.nanmax(lst), "LST Mean": np.nanmean(lst)
        })
        plot_lst_refined(lst, f'Peta LST {name} Tahun {year}')

# ============================================================
# 3. OUTPUT TABEL STATISTIK
# ============================================================
df_lst = pd.DataFrame(table_data_lst)
for r in ["Sidoarjo", "Control", "Impact"]:
    print(f"\n--- Statistik LST: {r} ---")
    display(df_lst[df_lst['Wilayah'] == r].drop(columns=['Wilayah']))

!pip install matplotlib-scalebar
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
from matplotlib_scalebar.scalebar import ScaleBar
import pandas as pd

# ====================================================
# URBAN & RURAL ZONING PROCESSING FOR ALL YEARS
# ====================================================

results_zoning = []

for year in ["2005", "2010", "2015", "2025"]:
    if year not in results_bands: continue

    data = results_bands[year]
    nir, red = data['nir'], data['red']
    thermal = data['thermal']
    sidoarjo_mask = data['sidoarjo_mask']

    # 1. Recalculate LST
    ndvi = (nir - red) / (nir + red + 1e-10)
    pv = np.clip(((ndvi - 0.2) / (0.5 - 0.2))**2, 0, 1)
    lse = np.where(ndvi < 0, 0.985, np.where(ndvi <= 0.2, 0.97, np.where(ndvi <= 0.5, 0.986 + 0.004 * pv, 0.99)))

    bt = thermal * 0.00341802 + 149.0
    lst_k = bt / (1 + (10.895e-6 * bt / 1.438e-2) * np.log(np.clip(lse, 0.001, 1)))
    lst_c = lst_k - 273.15

    # 2. Klasifikasi Urban/Rural
    urban_mask = (ndvi < 0.2) & sidoarjo_mask
    rural_mask = (ndvi >= 0.2) & sidoarjo_mask

    t_urban = np.nanmean(lst_c[urban_mask])
    t_rural = np.nanmean(lst_c[rural_mask])

    results_zoning.append({
        "Tahun": year,
        "Urban Mean LST (°C)": t_urban,
        "Rural Mean LST (°C)": t_rural
    })

    # 3. Visualisasi dengan Auto-Cropping
    zone_map = np.full(ndvi.shape, np.nan)
    zone_map[urban_mask] = 1
    zone_map[rural_mask] = 2

    # Cropping Logic
    rows = np.any(~np.isnan(zone_map), axis=1)
    cols = np.any(~np.isnan(zone_map), axis=0)
    if np.any(rows):
        rmin, rmax = np.where(rows)[0][[0, -1]]
        cmin, cmax = np.where(cols)[0][[0, -1]]
        pad = 20
        cropped = zone_map[max(0,rmin-pad):min(zone_map.shape[0],rmax+pad),
                           max(0,cmin-pad):min(zone_map.shape[1],cmax+pad)]

        cmap_suhi = ListedColormap(['#d7191c', '#1a9641'])
        cmap_suhi.set_bad(color='white')

        fig, ax = plt.subplots(figsize=(10, 8))
        img = ax.imshow(cropped, cmap=cmap_suhi, vmin=1, vmax=2)

        cbar = plt.colorbar(img, ax=ax, orientation='horizontal', pad=0.1, fraction=0.04)
        cbar.set_ticks([1.25, 1.75])
        cbar.set_ticklabels(['Urban (NDVI < 0.2)', 'Rural (NDVI >= 0.2)'])
        cbar.set_label('Zonasi Klasifikasi')

        ax.set_title(f"Peta Zonasi Urban-Rural Sidoarjo Tahun {year}", fontsize=13)
        ax.axis('off')
        plt.tight_layout()
        plt.show()

# 4. Display Tabel Ringkasan
print("\n--- Ringkasan Statistik LST per Zona Sidoarjo ---")
display(pd.DataFrame(results_zoning))

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# ==========================================
# 1. KONFIGURASI & PENYIMPANAN STATISTIK
# ==========================================
suhi_statistics_full = []
target_years_suhi = ["2005", "2010", "2015", "2025"]

for year in target_years_suhi:
    if year not in results_bands: continue

    # Ambil data utama & control
    d_sid = results_bands[year]
    d_ctrl = results_bands[f'Control {year}']

    # Persiapkan Mask
    m_sid = d_sid['sidoarjo_mask']
    m_ctrl = d_ctrl['sidoarjo_mask']
    m_imp = m_sid & (~m_ctrl)

    # Mapping Wilayah
    regions = {
        "Sidoarjo": (d_sid, m_sid),
        "Control": (d_ctrl, m_ctrl),
        "Impact": (d_sid, m_imp)
    }

    for reg_name, (data, mask) in regions.items():
        nir, red, thermal = data['nir'], data['red'], data['thermal']

        # Hitung LST & NDVI Dasar
        ndvi = (nir - red) / (nir + red + 1e-10)
        pv = np.clip(((ndvi - 0.2) / (0.5 - 0.2))**2, 0, 1)
        lse = np.where(ndvi < 0, 0.985, np.where(ndvi <= 0.2, 0.97, np.where(ndvi <= 0.5, 0.986 + 0.004 * pv, 0.99)))
        bt = thermal * 0.00341802 + 149.0
        lst_k = bt / (1 + (10.895e-6 * bt / 1.438e-2) * np.log(np.clip(lse, 0.001, 1)))
        lst = lst_k - 273.15

        # Definisi Urban/Rural (Gunakan d_sid untuk referensi Rural yang konsisten)
        urban_mask = (ndvi < 0.2) & mask
        rural_ref_mask = (ndvi > 0.4) & mask

        # Jika Rural kosong di wilayah kecil (Impact), gunakan rata-rata rural dari Sidoarjo sebagai baseline
        if np.nansum(rural_ref_mask) < 10:
            ndvi_full = (d_sid['nir'] - d_sid['red']) / (d_sid['nir'] + d_sid['red'] + 1e-10)
            rural_ref_mask = (ndvi_full > 0.4) & d_sid['sidoarjo_mask']

        rural_mean = np.nanmean(lst[rural_ref_mask])
        urban_mean = np.nanmean(lst[urban_mask])
        suhi_intensity = urban_mean - rural_mean

        # Hitung SUHI Spasial
        suhi_spatial = np.where(mask, lst - rural_mean, np.nan)

        # Simpan Statistik
        suhi_statistics_full.append({
            'Tahun': year, 'Wilayah': reg_name,
            'Urban Mean': urban_mean, 'Rural Mean': rural_mean,
            'SUHI Intensity': suhi_intensity,
            'SUHI Min': np.nanmin(suhi_spatial), 'SUHI Max': np.nanmax(suhi_spatial)
        })

        # ==========================================
        # 2. PLOTTING (AUTO-CROPPED)
        # ==========================================
        rows = np.any(~np.isnan(suhi_spatial), axis=1)
        cols = np.any(~np.isnan(suhi_spatial), axis=0)

        if np.any(rows):
            rmin, rmax = np.where(rows)[0][[0, -1]]
            cmin, cmax = np.where(cols)[0][[0, -1]]
            pad = 20
            cropped = suhi_spatial[max(0,rmin-pad):min(suhi_spatial.shape[0],rmax+pad),
                                   max(0,cmin-pad):min(suhi_spatial.shape[1],cmax+pad)]

            fig, ax = plt.subplots(figsize=(10, 8))
            im = ax.imshow(cropped, cmap='RdBu_r', vmin=-5, vmax=5)
            cbar = plt.colorbar(im, ax=ax, orientation='horizontal', pad=0.1, fraction=0.04)
            cbar.set_label('SUHI (°C) [LST - Rural Mean]')
            ax.set_title(f'Peta Distribusi Spasial SUHI {reg_name} Tahun {year}\nIntensitas: {suhi_intensity:.2f} °C', fontsize=12)
            ax.axis('off')
            plt.show()

# ==========================================
# 3. TABEL RINGKASAN FULL
# ==========================================
df_suhi_full = pd.DataFrame(suhi_statistics_full)
for reg in ["Sidoarjo", "Control", "Impact"]:
    print(f"\n--- Statistik SUHI Spasial: {reg} ---")
    display(df_suhi_full[df_suhi_full['Wilayah'] == reg].drop(columns=['Wilayah']))

import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))

plt.plot(
    suhi_df['Year'],
    suhi_df['SUHI Intensity'],
    marker='o',
    linewidth=2
)

for x, y in zip(
    suhi_df['Year'],
    suhi_df['SUHI Intensity']
):
    plt.text(
        x,
        y + 0.05,
        f'{y:.2f}',
        ha='center'
    )

plt.xlabel('Tahun')
plt.ylabel('SUHI (°C)')

plt.title(
    'Tren Intensitas SUHI Kabupaten Sidoarjo'
)

plt.grid(True)

plt.tight_layout()

plt.show()